[tool.poetry]
name = "lawrogue"
version = "0.1.0"
description = ""
authors = ["Ash Griffiths <46426454+AshGriffiths@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
